baseURL = 'https://hlsl-tc57.github.io/website/'
languageCode = 'en-us'
title = 'Ecma TC57 - HLSL'
theme = 'archie'
pagination.pagerSize = 5

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  menu_style = "slide-menu"
  github_doc_repository = "https://github.com/hlsl-tc57/website/"
  github_doc_repository_branch = "main"
  github_doc_repository_path = ""
  customcss = ["style.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    noClasses = false

[languages]
  [languages.en]
    languageName = "English"
    title = "TC57"

    [languages.en.params]
      subtitle = "Ecma TC57 - HLSL- Blog"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "TC57"

[module]
  [[module.mounts]]
    source = './content'
    target= 'content'

  [[module.mounts]]
    source = 'monthly'
    target = 'content/monthly'

  [[module.mounts]]
    source = 'assets'
    target = 'content/assets'

  [[module.mounts]]
    source = '_index.md'
    target = 'content/_index.md'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Monthly"
  url = "/monthly"
  weight = 2
